services:

  wikidocs:
    image: zavy86/wikidocs
    container_name: wikidocs
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8000:80
    volumes:
      - ./wikidocs-data:/datasets